# Generated by Django 4.2.15 on 2024-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='weapon',
            field=models.ManyToManyField(to='main_app.weapon'),
        ),
    ]
