# Generated by Django 4.2.15 on 2024-08-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ninja_weapon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='weapon',
            new_name='weapons',
        ),
    ]
